server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;

    location ~* \.(js|mjs)$ {
        default_type application/javascript;
        add_header Cache-Control "no-store" always;
        add_header X-Content-Type-Options "nosniff" always;
    }

    location ~* \.(html|css)$ {
        add_header Cache-Control "no-store" always;
        add_header X-Content-Type-Options "nosniff" always;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
